services:
  prompt-injection-api:
    environment:
      NODE_ENV: development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 3001
    build: .
    image: "scottlogic/prompt-injection-api"
    ports:
      - "3001:3001"
