# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server Code Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: ./backend

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: backend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci --no-audit
      - name: Run job
        run: |
          npx eslint .
          npx prettier . --check

  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: backend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci --no-audit
      - name: Run job
        run: |
          npm run build
          npm test
