name: Cloud Code Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
    paths:
      - 'cloud/**'

defaults:
  run:
    working-directory: ./cloud

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .prettierrc
            cloud
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './cloud/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci --no-audit
      - name: Run job
        run: |
          npm run codecheck
