# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UI Code Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci
      - name: Run job
        run: |
          npx eslint .
          npx stylelint '**/*.css'
          npx prettier . --check

  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      - name: Install dependencies
        run: |
          npm ci
      - name: Run job
        run: |
          npm run build
          npm test
