# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UI Code Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Run job
        run: |
          npm ci
          npx eslint .
          npx stylelint '**/*.css'
          npx prettier . --check
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Run nob
        run: |
          npm ci
          npm run build
          npm test
