# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: K6 load-testing Code Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'k6/**'

defaults:
  run:
    working-directory: ./k6

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: k6
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./k6/package-lock.json"
      - name: Run job
        run: |
          npm ci
          npx eslint .
          npx prettier . --check
